apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-todo-app
  template:
    metadata:
      labels:
        app: react-todo-app
    spec:
      containers:
      - name: react-todo-app
        image: utkarshkdocker/todo-app:latest
        ports:
        - containerPort: 80